<a href="https://colab.research.google.com/github/kim07084/-/blob/main/numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 아무문장
아무문장


In [2]:
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [3]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [4]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [5]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1][2]

3.14

In [7]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [8]:
arVal[0][2]

't'

In [9]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [10]:
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [11]:
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [12]:
arVal.sum()

AttributeError: ignored

In [13]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [15]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [16]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [17]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [18]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [19]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [20]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [21]:
arVal.sum(axis=1) # 축(axis)이 1일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [22]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
# pandas import
import pandas as pd
pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [25]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [26]:
pandas_series[0]

30

In [27]:
pandas_series[0][1]

IndexError: ignored

In [28]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [29]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [30]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [31]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [32]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [34]:
# DataFrame의 각 column 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [33]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [35]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [36]:
# column 삭제
del df['score']

In [37]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: ignored

In [39]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [40]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [41]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [42]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']
df

A         B         C         D         E
0  0.666331  2.067875  1.407611 -2.030997  0.156707
1  0.457703 -0.314531 -0.007009  0.097756 -1.131776
2  1.355955  0.448383 -0.581431  0.230138 -0.573966
3 -0.442053  1.241101  0.456864 -0.608723  0.061490
4  0.323447 -1.372583  0.976513  0.745082  1.294301

In [43]:
# 최대값
df.max()

A    1.355955
B    2.067875
C    1.407611
D    0.745082
E    1.294301
dtype: float64

In [44]:
# 최소값
df.min()

A   -0.442053
B   -1.372583
C   -0.581431
D   -2.030997
E   -1.131776
dtype: float64

In [45]:
# 평균
df.mean()

A    0.472277
B    0.414049
C    0.450510
D   -0.313349
E   -0.038649
dtype: float64

In [46]:
# 표준편차
df.std()

A    0.647477
B    1.336340
C    0.785332
D    1.074968
E    0.909181
dtype: float64

In [47]:
# 누적값
df.cumsum()

A         B         C         D         E
0  0.666331  2.067875  1.407611 -2.030997  0.156707
1  1.124034  1.753344  1.400602 -1.933241 -0.975069
2  2.479989  2.201728  0.819170 -1.703103 -1.549036
3  2.037936  3.442828  1.276034 -2.311827 -1.487545
4  2.361384  2.070246  2.252548 -1.566745 -0.193244

In [48]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.472277  0.414049  0.450510 -0.313349 -0.038649
std    0.647477  1.336340  0.785332  1.074968  0.909181
min   -0.442053 -1.372583 -0.581431 -2.030997 -1.131776
25%    0.323447 -0.314531 -0.007009 -0.608723 -0.573966
50%    0.457703  0.448383  0.456864  0.097756  0.061490
75%    0.666331  1.241101  0.976513  0.230138  0.156707
max    1.355955  2.067875  1.407611  0.745082  1.294301

In [49]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0  0.666331  2.067875  1.407611 -2.030997  0.156707        X
1  0.457703 -0.314531 -0.007009  0.097756 -1.131776        Y
2  1.355955  0.448383 -0.581431  0.230138 -0.573966        X
3 -0.442053  1.241101  0.456864 -0.608723  0.061490        Y
4  0.323447 -1.372583  0.976513  0.745082  1.294301        Z

In [50]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X         1.011143  1.258129  0.413090 -0.900430 -0.208630
Y         0.007825  0.463285  0.224928 -0.255484 -0.535143
Z         0.323447 -1.372583  0.976513  0.745082  1.294301